services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: test-php
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www:cached
    depends_on:
      - database
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=dblogin
      - DB_USERNAME=user
      - DB_PASSWORD=password
  database:
    image: mysql:8.0
    container_name: test-database
    environment:
      MYSQL_DATABASE: dblogin
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: